export const data = [
  {
    code: "P3772",
    name: "Product 01",
    category: "Sunglasses",
    shop: "Kurunegala",
    status: "In Stock",
    qty: 10,
  },
  {
    code: "P5234",
    name: "Product 02",
    category: "Frame",
    shop: "Polonnaruwa",
    status: "In Stock",
    qty: 5,
  },
  {
    code: "P5235",
    name: "Product 03",
    category: "Frame",
    shop: "Kandy",
    status: "In Stock",
    qty: 15,
  },
  {
    code: "P7843",
    name: "Product 04",
    category: "Sunglasses",
    shop: "Kurunegala",
    status: "In Stock",
    qty: 20,
  },
  {
    code: "P6436",
    name: "Product 05",
    category: "Sunglasses",
    shop: "Kandy",
    status: "In Stock",
    qty: 8,
  },
  {
    code: "P7437",
    name: "Product 06",
    category: "Frame",
    shop: "Polonnaruwa",
    status: "Out of Stock",
    qty: 10,
  },
  {
    code: "P9873",
    name: "Product 07",
    category: "Sunglasses",
    shop: "Kandy",
    status: "In Stock",
    qty: 12,
  },
  {
    code: "P2346",
    name: "Product 08",
    category: "Sunglasses",
    shop: "Kandy",
    status: "In Stock",
    qty: 8,
  },
  {
    code: "P4435",
    name: "Product 09",
    category: "Frame",
    shop: "Kurunegala",
    status: "In Stock",
    qty: 12,
  },
  {
    code: "P7534",
    name: "Product 10",
    category: "Sunglasses",
    shop: "Polonnaruwa",
    status: "Out of Stock",
    qty: 8,
  },
];

export const shops = [
  {
    name: "Kurunegala",
    status: "Active",
    qty: 125,
  },
  {
    name: "Kandy",
    status: "Active",
    qty: 66,
  },
  {
    name: "Polonnaruwa",
    status: "Active",
    qty: 70,
  },
];
